project/views/quiz.py
from flask import render_template, request, Blueprint, url_for
from flask_login.utils import login_required, current_user

from project.models.quiz import Question

quiz = Blueprint('quiz', __name__)


@quiz.route('/quiz', methods=['GET', 'POST'])
@login_required
def home():
    context = dict(
        key_name='answer',
        form={},
        questions=Question.fetch_quiz()
    )
    if request.method == 'POST':
        answered_questions, score = Question.check_answers(key_name=context['key_name'],
                                                           answers=request.form,
                                                           current_user=current_user)
        context.update(dict(
            form=request.form,
            questions=answered_questions,
            show_answer=True,
            score=score
        ))
    return render_template('pages/movies.html', **context)

project/templates/pages/home.html
{% extends 'layouts/main.html' %}
{% block title %}Movie Quiz{% endblock %}
{% block content %}

<div>
  <h2>Movie Quiz</h2>
    <p>
      The movie questions are based on TOP 250 MOVIES ON THE IMDB.
    </p>
    <a href="{{ url_for('quiz.home') }}" class="btn btn-secondary btn-lg">
      Take a Movie Quiz
    </a>

    <table style="margin-top: 1em;" class="table">
      <thead>
        <tr>
          <th>Name</th>
          <th>Score</th>
        </tr>
      </thead>
      <tbody>
        {% for score in scores %}
          <tr>
            <td>{{ score.user.username }} </td>
            <td>{{ score.score }}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
    <nav>
      <ul class="pagination">
        {% if prev_url %}
          <li class="page-item"><a class="page-link" href="{{ prev_url }}">Previous</a></li>
        {% else %}
          <li class="page-item"><a class="page-link" aria-disabled="true">Previous</a></li>
        {% endif %}
        <li class="page-item active" aria-current="page">
          <span class="page-link">
            {{page}}
            <span class="sr-only">(current)</span>
          </span>
        </li>
        {% if next_url %}
          <li class="page-item"><a class="page-link" href="{{ next_url }}">Next</a></li>
        {% else %}
          <li class="page-item"><a class="page-link" aria-disabled="true">Next</a></li>
        {% endif %}
      </ul>
    </nav>
</div>

{% endblock %}

project/templates/pages/movies.html
{% extends 'layouts/main.html' %}
{% block title %}Movie Quiz{% endblock %}
{% block content %}

<div>
    <h2>Movie Quiz</h2>
    <p>
        {% if show_answer %}
        <h4>You scored {{ score }}. Congrats!</h4>
        <form>
        {% else %}
        <form method="POST">
        {% endif %}
            {% for question in questions %}
                {% set value = form.get(key_name+question.id|string, "") %}
                <p>
                    {{ question.question }}<br>
                    <input name="{{ key_name }}{{ question.id }}"
                           id="{{ key_name }}{{ question.id }}"
                           value="{{ value }}"
                           placeholder="Answer" />
                    {% if show_answer %}
                        {% if question.answer == value %}
                            <span class="success"> Correct
                        {% else %}
                            <span class="error"> {{ question.answer }}
                        {% endif %}
                        </span>
                    {% endif %}
                </p>
            {% endfor %}
            {% if show_answer %}
                <button type="submit" disabled>Submit</button>
            {% else %}
                <button type="submit">Submit</button>
            {% endif %}
        </form>
    </p>
</div>

{% endblock %}