project/views/users.py
from flask import render_template, redirect, flash, Blueprint
from flask import request
from flask.globals import current_app
from flask.helpers import url_for
from flask_login import login_user, login_required, logout_user

from project.forms import LoginUserForm, RegisterUserForm, ActivateUserForm
from project.models import Score
from project.models.users import User
from project.views.utils import logout_required

users = Blueprint('users', __name__)


@users.route('/', methods=['GET'])
@login_required
def home():
    page = request.args.get('page', 1, type=int)
    paginated_scores = Score.query.order_by(Score.score.desc()).paginate(
        page, current_app.config.get('PAGE_SIZE', 5), False
    )
    next_url = url_for('users.home', page=paginated_scores.next_num) \
        if paginated_scores.has_next else None
    prev_url = url_for('users.home', page=paginated_scores.prev_num) \
        if paginated_scores.has_prev else None
    context = dict(
        scores=paginated_scores.items,
        prev_url=prev_url,
        next_url=next_url,
        page=page,
    )
    return render_template('pages/home.html', **context)


@users.route('/register', methods=['GET', 'POST'])
@logout_required
def register():
    form = RegisterUserForm(request.form)
    if request.method == 'POST' and form.validate():
        user = form.save(form.data)
        flash(f'User {user.username} Registered successfully!')
        return redirect(url_for('users.login'))
    return render_template('forms/register.html', form=form)


@users.route('/activate', methods=['GET', 'POST'])
@logout_required
def activate():
    form = ActivateUserForm(request.form)
    if request.method == 'POST' and form.validate():
        user = form.save(form.data)
        if not user:
            flash('Could not find the code.')
            return redirect('/activate')
        else:
            flash(f'User {user.username} created successfully! Please login!')
        return redirect(url_for('users.login'))
    return render_template('forms/activate.html', form=form)


@users.route('/login', methods=['GET', 'POST'])
@logout_required
def login():
    form = LoginUserForm(request.form)
    if request.method == 'POST' and form.validate():
        username = form.data['username']
        login_user(User.get_by_username(username))
        flash(f'Welcome {username}!')
        return redirect('/')
    return render_template('forms/login.html', form=form)


@users.route('/logout', methods=['GET'])
@login_required
def logout():
    logout_user()
    return redirect(url_for('users.login'))


@users.errorhandler(500)
def internal_error(error):
    #db_session.rollback()
    return render_template('errors/500.html'), 500


@users.errorhandler(404)
def not_found_error(error):
    return render_template('errors/404.html'), 404

project/templates/layouts/main.html
<!doctype html>
<html>
    <head>
        <meta charset="utf-8">
        <title>{% block title %}{% endblock %}</title>

        <!-- meta -->
        <meta name="viewport" content="width=device-width,initial-scale=1">
        <!-- /meta -->

        <!-- styles -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link type="text/css" rel="stylesheet" href="/static/css/customs.css" />
        <!-- /styles -->

        <!-- favicons -->

        <!-- /favicons -->

        <!-- scripts -->
        <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
        <!-- /scripts -->

    </head>
    <body>
         <!-- Navbar -->
         <nav class="navbar navbar-expand-md navbar-light fixed-top">
             <a class="navbar-brand" href="/">Movie Quiz</a>

            <div class="collapse navbar-collapse" id="navbarsExampleDefault">
                <ul class="navbar-nav mr-auto">
                    <!--<li class="nav-item active">-->
                        <!--<a class="nav-link" href="">Home </a>-->
                    <!--</li>-->
                </ul>
                <div>
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item">
                            <a class="nav-link btn btn-outline-danger" href="{{ url_for('users.logout') }}">Logout </a>
                        </li>
                    </ul>
                </div>
            </div>
         </nav>
        <main role="main" class="container">
            <!-- Begin page content -->
            {% with messages = get_flashed_messages() %}
                {% if messages %}
                    {% for message in messages %}
                        <div class="alert alert-info alert-dismissible fade show" role="alert">
                            {{ message }}
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                    {% endfor %}
                {% endif %}
            {% endwith %}

            {% block content %}{% endblock %}

        </main>

    </body>
</html>